In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("movies.csv")

In [3]:
data.describe()

,budge,gross,comment_count,view_count,like_count,year
count,5.530000e+02,5.530000e+02,553.000000,5.530000e+02,5.530000e+02,553.000000
mean,4.504289e+07,6.011663e+07,8521.940325,1.129772e+07,6.968218e+04,2016.826401
std,5.705363e+07,9.762178e+07,28349.410314,1.716151e+07,1.973409e+05,0.811304
min,2.700000e+04,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,2016.000000
25%,8.500000e+06,3.877922e+06,757.000000,2.406436e+06,7.924000e+03,2016.000000
50%,2.200000e+07,2.702028e+07,2290.000000,6.314870e+06,2.355600e+04,2017.000000
75%,5.500000e+07,6.720962e+07,6791.000000,1.432265e+07,6.189800e+04,2018.000000
max,3.170000e+08,7.000596e+08,464912.000000,2.299176e+08,3.553094e+06,2018.000000